- name: Build & Deploy Dockerized Static Website
  hosts: web
  gather_facts: false
  remote_user: root

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Copy app files to remote server
      synchronize:
        src: ./app/
        dest: /root/project/
        recursive: yes

    - name: Build Docker Image
      community.docker.docker_image:
        name: mico
        tag: latest
        build:
          path: /root/project
        state: present

    - name: Run Docker Container
      community.docker.docker_container:
        name: mico-container
        image: mico:latest
        ports:
          - "81:80"
        state: started
        restart_policy: always
