- name: Build & Deploy Dockerized Static Website
  hosts: web
  become: yes
  gather_facts: false
  remote_user: root

  tasks:
    - name: Install Docker using official script
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Copy app files to remote server
      synchronize:
        src: ./app/
        dest: /root/project/
        recursive: yes

    - name: Build Docker Image
      community.docker.docker_image:
        name: mico
        tag: latest
        build:
          path: /root/project
        state: present

    - name: Run Docker Container
      community.docker.docker_container:
        name: mico-container
        image: mico:latest
        ports:
          - "80:80"
        state: started
        restart_policy: always
